# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsecret-1-dev
      - libsodium-dev

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: "R CMD check"
      r: oldrel
    - r: release
    - r: devel

    - stage: deploy
      name: covr
      r: release
      script:
        - Rscript -e "remotes::install_cran('covr')"
        - Rscript -e "covr::codecov()"

    - stage: deploy
      name: pkgdown
      r: release
      if: branch IN (master, travis) AND repo = rich-iannone/blastula AND type = push
      script:
      - Rscript -e "remotes::install_cran(c('pkgdown', 'devtools'))"
      - Rscript -e "devtools::install()"
      - Rscript -e "Sys.setenv(FULLNAME = 'Richard Iannone'); pkgdown::build_site()"
      - Rscript -e "remove.packages(devtools::as.package('.')$package)"
      deploy:
        provider: pages
        script: Rscript -e 'devtools::install()'
        local-dir: docs
        skip-cleanup: true
        keep-history: false
        on:
          all_branches: true
        github-token:
          secure: "hop2WrveJmSmnoHqlVaXs5rXN4nHXIhRO7qQY/z+p4wF+DcpvVQXTq2bFUU33RnxbsZYwcVO0UKGycnEwRgeSO1ooWetJcr/wTkRv2SIGoiRjYVhCbpEM3Gq3lWHuGStQElnwRctZCSL0+TjihrKGBe9vhmFPaiMeTptNDd60rujuVFBIThScfyqChmAhqd9/hGagfaBTnXnCJB4ldSOBu1NcA1s0VGnrE/Dioz3cnyqEaEadLrbQMJCX+pFnwlE2sDuDk1XxBIpTGQKlDumW8XHPpi82+LTPNsiH1cJchhITMuLXBZp6YjOguBRBdZFDEU1RwAtQyK+SRMPs2j4LYDYrB3K9ySFI9hlnh59K212RpRYGsRSbth/rtAsaYNUXImyCjAiHGO2PXjsJ31uPligx2srpu+3JBVo5gxYGDBlMbTm2mbQlERbrAhiy8M/pO3pu2uQ1Zy44diAEKR9TsyovklSn+D3WDl23OJDxy0Hal3YclP6bXnH6tFBHrwJ8AalA4751/8UADuZyp4v3o2Dfh3YdIZp0vafmwqymqPsV1rax0DabNAdHKdu5Hym53jEE0DMfwqb2YoHs+h4DZM1vdYGevVzHXrAHn2768DJBgo36ubxeZzcNnmOteuzq4mghVq1YjRTy13hMgV95KWtZx+oFeYpmH/ZC/TIb9U="
